language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git python-dev libxml2-dev libxslt1-dev zlib1g-dev
install:
  - pip install hot
script: hot test

